# Some attributes are required conditionally. These are annotated via comments.

# Required settings
experiment_name: 'min_with_20'
mode: 'from_orthogroups'  # 'from_genome', 'from_orthogroups'
objective: 'max'
scorer: 'chopchop'  # TODO add deepguide - options: 'chopchop', 'random', 'dummy' -- dummy assigns a score of 1 to all guides
solver_engine: 'GLOP'
cas: 'cas9'  # options: 'cas9'
pam_regex: r'(?=(GG))'  # PAM for cas9 is: r'(?=(GG))'

beta: 10  # The final size of the guides set must be <= than this. Think of it as your budget.

#  Search all combinatorial possibilities unless there are more feasible solutions than this (then use randomized rounding)
exhaustive_threshold: 0

# Only used if the number of feasible guides is above the exhaustive_threshold.
# How many times to run the randomized rounding algorithm?
num_trials: 10000

graph: True
output_csv: True
traceback: False

# Required for all modes
input_species_path: 'data/input/input_species_20.csv'
input_genomes_directory: 'data/input/genomes/'
output_directory: 'data/output/'

# Required if mode is set to 'from_orthogroups' -- ignored otherwise
orthogroups_path: 'data/input/orthogroups/Orthogroups.tsv'
input_cds_directory: 'data/input/cds/orthogroups/'  # Files inside must end with _cds.fna or _cds.faa or _cds.fasta

# Required if scorer is set to 'chopchop' -- ignored otherwise
absolute_path_to_chopchop: '/home/amohs002/projects/research/chopchop/chopchop.py'
absolute_path_to_bowtie_build: '/home/amohs002/projects/research/chopchop/bowtie/bowtie-build'
absolute_path_to_genomes_directory: '/home/amohs002/projects/research/ALLEGRO/data/input/genomes/'
chopchop_scoring_method: 'DOENCH_2016'