# left here -- link coversetcpp with ortools
# then link both to cythonpython


# --------------------------------------------------------------------
# General settings
# --------------------------------------------------------------------
experiment_name: 'cython_test_3'
mode: 'from_genome'  # 'from_genome', 'from_cds'
objective: 'min'  # default: 'max' uses beta -- 'min' does not use beta
scorer: 'dummy'  # options: default: 'chopchop', 'dummy'
                 # dummy assigns a score of 1.0 to all guides
solver_engine: 'GLOP'
beta: 0  # Integer value: Used with objective: 'max'
         # The final size of the guides set must be <= than this. Think of it as your budget.

# Integer value: Search all combinatorial possibilities unless there are more
# feasible solutions than this (then use randomized rounding)
exhaustive_threshold: 5

# If False, discards guides with protospacers with 2 or fewer unique nucleotides
# For example, this cas9 guide will not be in the output: ACCACCACCACCACCACCAC
include_repetitive: False

# Integer value: Only used if the number of feasible guides is above the exhaustive_threshold.
# How many times to run the randomized rounding algorithm?
num_trials: 10000

graph: False
output_csv: True
save_temp_data_to: 'ram'  # options: 'ram', 'database'.
                           # Use database if running out of ram. Database is slower.
# --------------------------------------------------------------------


# --------------------------------------------------------------------
# Endonuclease settings
# --------------------------------------------------------------------
cas: 'cas9'  # default: 'cas9'
pam: 'NGG'  # default for cas9: 'NGG'
            # Supports 'NGG' which looks for 'A/C/T/G' + 'GG' 
            # Any other PAM will be treated as a literal string.
protospacer_length: 20  # Integer, default: 20
context_toward_five_prime: 5  # Integer, default: 5
context_toward_three_prime: 3  # Integer, default: 3
# --------------------------------------------------------------------


# --------------------------------------------------------------------
# Path Settings
# --------------------------------------------------------------------
input_species_path: 'data/input/dummy.csv'
input_genomes_directory: 'data/input/genomes/'
output_directory: 'data/339_output_genomes_ns/'

# Required if mode is set to 'from_cds' -- ignored otherwise -- default: input_cds_directory: 'data/input/cds/orthogroups/''
input_cds_directory: 'data/input/cds/'  # Files inside must end with _cds.fna or _cds.faa or _cds.fasta

# Required if scorer is set to 'chopchop' -- ignored otherwise
chopchop_scoring_method: 'DOENCH_2016'
absolute_path_to_chopchop: '/home/amohs002/projects/research/chopchop/'  # directory only
absolute_path_to_genomes_directory: '/home/amohs002/projects/research/ALLEGRO/data/input/genomes/'