# All attributes must be valid and are required at the same time.

cds_directory: 'data/input/cds/'
ortho_path: 'data/input/orthogroups/Orthogroups.tsv'
prot_id_regex: '\[protein_id=(.*?)\]'

auxotroph_names: [
  'LYS2', 'LYS5', 'MET17', 'TRP1', 'URA3', 'FCY1', 'GAP1', 'CAN1'
]

auxotroph_tags: []

species: 'saccharomyces_cerevisiae'  # species must match with species.fna in cds path and a column name in Orthogroups.tsv
gene_names: [
  'LYS2', 'LYS5', 'MET17', 'TRP1', 'URA3', 'FCY1', 'GAP1', 'CAN1'
]  # Pick an auxotroph gene from the list above to generate the cds for.
